BEGIN;
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"x"},{"key":"field_2","label":"y"}]}'::jsonb WHERE type_id = 'G11-ALG-001';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"real"},{"key":"field_2","label":"imaginary"}]}'::jsonb WHERE type_id = 'G11-NUM-001';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"tens"},{"key":"field_2","label":"ones"}]}'::jsonb WHERE type_id = 'G2-NUM-014';
UPDATE task_type SET widget_config = '{"field_count":3,"fields":[{"key":"field_1","label":"hundreds"},{"key":"field_2","label":"tens"},{"key":"field_3","label":"ones"}]}'::jsonb WHERE type_id = 'G2-NUM-052';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"quotient"},{"key":"field_2","label":"remainder"}]}'::jsonb WHERE type_id = 'G3-NUM-011';
UPDATE task_type SET widget_config = '{"field_count":4,"fields":[{"key":"field_1","label":"thousands"},{"key":"field_2","label":"hundreds"},{"key":"field_3","label":"tens"},{"key":"field_4","label":"ones"}]}'::jsonb WHERE type_id = 'G4-NUM-002';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"quotient"},{"key":"field_2","label":"remainder"}]}'::jsonb WHERE type_id = 'G4-NUM-010';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"quotient"},{"key":"field_2","label":"remainder"}]}'::jsonb WHERE type_id = 'G4-NUM-029';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"quotient"},{"key":"field_2","label":"remainder"}]}'::jsonb WHERE type_id = 'G6-NUM-004';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"x"},{"key":"field_2","label":"y"}]}'::jsonb WHERE type_id = 'G7-ALG-002';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"slope"},{"key":"field_2","label":"y-intercept"}]}'::jsonb WHERE type_id = 'G7-ALG-020';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"x"},{"key":"field_2","label":"y"}]}'::jsonb WHERE type_id = 'G7-ALG-023';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"x"},{"key":"field_2","label":"y"}]}'::jsonb WHERE type_id = 'G7-ALG-024';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"x"},{"key":"field_2","label":"y"}]}'::jsonb WHERE type_id = 'G7-ALG-025';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"adult tickets"},{"key":"field_2","label":"child tickets"}]}'::jsonb WHERE type_id = 'G7-ALG-026';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"x"},{"key":"field_2","label":"y"}]}'::jsonb WHERE type_id = 'G8-ALG-005';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"adult tickets"},{"key":"field_2","label":"child tickets"}]}'::jsonb WHERE type_id = 'G8-ALG-006';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"x"},{"key":"field_2","label":"y"}]}'::jsonb WHERE type_id = 'G8-ALG-018';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"x-coordinate"},{"key":"field_2","label":"y-coordinate"}]}'::jsonb WHERE type_id = 'G8-FUN-006';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"x"},{"key":"field_2","label":"y"}]}'::jsonb WHERE type_id = 'G8-GEO-005';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"x"},{"key":"field_2","label":"y"}]}'::jsonb WHERE type_id = 'G8-GEO-006';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"x"},{"key":"field_2","label":"y"}]}'::jsonb WHERE type_id = 'G8-GEO-007';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"x"},{"key":"field_2","label":"y"}]}'::jsonb WHERE type_id = 'G8-GEO-023';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"x"},{"key":"field_2","label":"y"}]}'::jsonb WHERE type_id = 'G9-VEC-002';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"x"},{"key":"field_2","label":"y"}]}'::jsonb WHERE type_id = 'U-ALG-002';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"first component"},{"key":"field_2","label":"second component"}]}'::jsonb WHERE type_id = 'U-CAL-004';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"real"},{"key":"field_2","label":"imaginary"}]}'::jsonb WHERE type_id = 'U-CAL-020';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"real"},{"key":"field_2","label":"imaginary"}]}'::jsonb WHERE type_id = 'U-CAL-021';
UPDATE task_type SET widget_config = '{"field_count":2,"fields":[{"key":"field_1","label":"real"},{"key":"field_2","label":"imaginary"}]}'::jsonb WHERE type_id = 'U-CAL-022';
UPDATE task_type SET widget_config = '{"field_count":3,"fields":[{"key":"field_1","label":"x₁"},{"key":"field_2","label":"x₂"},{"key":"field_3","label":"x₃"}]}'::jsonb WHERE type_id = 'U-MAT-004';
COMMIT;
