UPDATE task_type
SET answer_widget = CASE validation_method
    WHEN 'EXACT-INT' THEN 'NUMERIC'
    WHEN 'TOL' THEN 'NUMERIC'
    WHEN 'EXACT-RAT' THEN 'FRACTION'
    WHEN 'BOOL' THEN 'CHOICE'
    WHEN 'TUPLE' THEN 'TUPLE_N'
    WHEN 'SET' THEN 'SET_LIST'
    WHEN 'MATRIX' THEN 'MATRIX_GRID'
    WHEN 'CANON' THEN 'STRUCTURED_CANON'
    WHEN 'CAS' THEN 'EXPRESSION'
END;
